from ...contracts.brain_region import BrainRegion

CORTICAL_REGIONS = (
    BrainRegion(
        name="Primary Auditory Cortex (Heschl's Gyrus)",
        abbreviation="A1_HG",
        hemisphere="bilateral",
        mni_coords=(44, -18, 8),
        function="Tonotopic frequency analysis and spectral feature extraction",
    ),
    BrainRegion(
        name="Superior Temporal Gyrus",
        abbreviation="STG",
        hemisphere="bilateral",
        mni_coords=(58, -22, 6),
        function="Pitch, melody, and harmonic processing",
    ),
    BrainRegion(
        name="Superior Temporal Sulcus",
        abbreviation="STS",
        hemisphere="bilateral",
        mni_coords=(52, -30, 4),
        function="Voice and timbre processing, audiovisual integration",
    ),
    BrainRegion(
        name="Inferior Frontal Gyrus",
        abbreviation="IFG",
        hemisphere="L",
        mni_coords=(-48, 14, 16),
        function="Syntactic and hierarchical structure processing in music",
    ),
    BrainRegion(
        name="Dorsolateral Prefrontal Cortex",
        abbreviation="DLPFC",
        hemisphere="bilateral",
        mni_coords=(42, 36, 28),
        function="Working memory for tonal and temporal sequences",
    ),
    BrainRegion(
        name="Ventromedial Prefrontal Cortex",
        abbreviation="vMPFC",
        hemisphere="bilateral",
        mni_coords=(0, 48, -12),
        function="Subjective value, autobiographical memory, and self-referential emotion",
    ),
    BrainRegion(
        name="Orbitofrontal Cortex",
        abbreviation="OFC",
        hemisphere="bilateral",
        mni_coords=(26, 34, -14),
        function="Hedonic evaluation and aesthetic judgment",
    ),
    BrainRegion(
        name="Anterior Cingulate Cortex",
        abbreviation="ACC",
        hemisphere="bilateral",
        mni_coords=(0, 28, 28),
        function="Conflict monitoring, expectation violation, and error detection",
    ),
    BrainRegion(
        name="Supplementary Motor Area",
        abbreviation="SMA",
        hemisphere="bilateral",
        mni_coords=(0, -4, 56),
        function="Internal rhythm generation and motor planning for beat",
    ),
    BrainRegion(
        name="Premotor Cortex",
        abbreviation="PMC",
        hemisphere="L",
        mni_coords=(-40, -8, 50),
        function="Sensorimotor coupling and rhythmic entrainment",
    ),
    BrainRegion(
        name="Angular Gyrus",
        abbreviation="Angular_Gyrus",
        hemisphere="bilateral",
        mni_coords=(46, -64, 30),
        function="Cross-modal integration, semantic processing, and musical meaning",
    ),
    BrainRegion(
        name="Temporal Pole",
        abbreviation="Temporal_Pole",
        hemisphere="bilateral",
        mni_coords=(40, 12, -34),
        function="Musical memory consolidation and familiar melody recognition",
    ),
)
