"""synchrony_reward -- Appraisal belief (SSRI, F9).

"The current reward signal generated by interpersonal synchrony
during musical interaction."

Observe: 0.70*f01:synchrony_reward + 0.30*P0:prefrontal_coupling
No predict/update cycle.

See Building/C3-Brain/F9-Social/beliefs/synchrony-reward.md
"""
from __future__ import annotations

from typing import Tuple

from torch import Tensor

from Musical_Intelligence.contracts.bases.belief import AppraisalBelief

# -- SSRI output indices ---------------------------------------------------
_F01_SYNCHRONY_REWARD = 0            # f01:synchrony_reward
_P0_PREFRONTAL_COUPLING = 7          # P0:prefrontal_coupling


class SynchronyReward(AppraisalBelief):
    """Appraisal belief: synchrony-driven reward signal."""

    NAME = "synchrony_reward"
    FULL_NAME = "Synchrony Reward"
    FUNCTION = "F9"
    MECHANISM = "SSRI"

    SOURCE_DIMS: Tuple[Tuple[str, float], ...] = (
        ("f01:synchrony_reward", 0.70),
        ("P0:prefrontal_coupling", 0.30),
    )

    def observe(self, mechanism_output: Tensor) -> Tensor:
        """Observe synchrony reward from SSRI output.

        Args:
            mechanism_output: ``(B, T, 11)`` SSRI output tensor.

        Returns:
            ``(B, T)`` observed synchrony reward.
        """
        return (
            0.70 * mechanism_output[:, :, _F01_SYNCHRONY_REWARD]
            + 0.30 * mechanism_output[:, :, _P0_PREFRONTAL_COUPLING]
        )
