#!/usr/bin/env python3
"""Generate beliefHorizonAtlas.ts from mechanism H³ demand specifications.

Reads all mechanism instances, extracts H³ demand tuples, groups by
horizon band (micro/meso/macro/ultra) and law (L0/L1/L2), and writes
a TypeScript file for the frontend.

Usage:
    python -m Lab.backend.generate_horizon_atlas
    # or from project root:
    python Lab/backend/generate_horizon_atlas.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Ensure project root is on sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from Lab.backend.belief_decomposition import (
    BAND_ORDER,
    HORIZON_BANDS,
    LAW_NAMES,
    LAW_ORDER,
    build_mechanism_atlas,
)
from Lab.backend.beliefs import get_beliefs_registry
from Lab.backend.pipeline import _collect_mechanism_instances


def main():
    print("[Atlas] Collecting mechanism instances...")
    nuclei = _collect_mechanism_instances()
    print(f"[Atlas] Found {len(nuclei)} mechanisms")

    print("[Atlas] Building mechanism atlas...")
    mech_atlas = build_mechanism_atlas(nuclei)
    print(f"[Atlas] {len(mech_atlas)} relay mechanisms with H³ demands")

    beliefs_reg = get_beliefs_registry()

    # Build per-belief atlas entries
    entries = []
    for belief in beliefs_reg:
        mech_name = belief["mechanism"]
        mech_info = mech_atlas.get(mech_name)
        if not mech_info:
            continue
        entries.append({
            "beliefIndex": belief["index"],
            "beliefName": belief["name"],
            "mechanism": mech_name,
            "totalDemands": mech_info["totalDemands"],
            "bands": mech_info["bands"],
            "laws": mech_info["laws"],
        })

    # Write TypeScript file
    out_path = PROJECT_ROOT / "Lab" / "frontend" / "src" / "data" / "beliefHorizonAtlas.ts"

    lines = [
        "/**",
        " * Auto-generated H³ demand atlas per belief.",
        " * Generated by Lab/backend/generate_horizon_atlas.py",
        " *",
        " * Maps each belief to its mechanism's H³ demand breakdown by",
        " * horizon band (micro/meso/macro/ultra) and law (memory/prediction/integration).",
        " */",
        "",
        "export type HorizonBand = 'micro' | 'meso' | 'macro' | 'ultra'",
        "",
        "export interface BandDemandInfo {",
        "  band: HorizonBand",
        "  tupleCount: number",
        "  horizons: number[]",
        "  laws: number[]",
        "}",
        "",
        "export interface LawDemandInfo {",
        "  law: 0 | 1 | 2",
        "  lawName: 'memory' | 'prediction' | 'integration'",
        "  tupleCount: number",
        "  horizons: number[]",
        "}",
        "",
        "export interface BeliefHorizonAtlas {",
        "  beliefIndex: number",
        "  beliefName: string",
        "  mechanism: string",
        "  totalDemands: number",
        "  bands: BandDemandInfo[]",
        "  laws: LawDemandInfo[]",
        "}",
        "",
        "export const BELIEF_HORIZON_ATLAS: Record<number, BeliefHorizonAtlas> = {",
    ]

    for entry in entries:
        idx = entry["beliefIndex"]
        bands_str = json.dumps(entry["bands"], separators=(", ", ": "))
        laws_str = json.dumps(entry["laws"], separators=(", ", ": "))
        lines.append(f"  {idx}: {{")
        lines.append(f"    beliefIndex: {idx},")
        lines.append(f"    beliefName: '{entry['beliefName']}',")
        lines.append(f"    mechanism: '{entry['mechanism']}',")
        lines.append(f"    totalDemands: {entry['totalDemands']},")
        lines.append(f"    bands: {bands_str},")
        lines.append(f"    laws: {laws_str},")
        lines.append(f"  }},")

    lines.append("}")
    lines.append("")

    # Band color constants
    lines.extend([
        "",
        "export const BAND_COLORS: Record<HorizonBand, string> = {",
        "  micro: '#00e5ff',",
        "  meso: '#00e676',",
        "  macro: '#ffd740',",
        "  ultra: '#ff5252',",
        "}",
        "",
        "export const BAND_LABELS: Record<HorizonBand, string> = {",
        "  micro: 'Micro (<250ms)',",
        "  meso: 'Meso (300ms–800ms)',",
        "  macro: 'Macro (1s–25s)',",
        "  ultra: 'Ultra (36s–981s)',",
        "}",
        "",
        "export const LAW_DECOMP_COLORS: Record<number, string> = {",
        "  0: '#448aff',  // L0 memory",
        "  1: '#ff6d00',  // L1 prediction",
        "  2: '#b388ff',  // L2 integration",
        "}",
        "",
        "export const LAW_DECOMP_LABELS: Record<number, string> = {",
        "  0: 'L0 Memory',",
        "  1: 'L1 Prediction',",
        "  2: 'L2 Integration',",
        "}",
        "",
    ])

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[Atlas] Written {len(entries)} belief entries to {out_path}")
    print("[Atlas] Done.")


if __name__ == "__main__":
    main()
